import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useUser } from "context/userContext";

const Home: NextPage = () => {
  const { loadingUser, user } = useUser();

  useEffect(() => {
    if (!loadingUser) {
      // You know that the user is loaded: either logged in or out!
      console.log(user);
    }
    // You also have your firebase app initialized
  }, [loadingUser, user]);

  if (loadingUser) return <p>loading ...</p>;

  return (
    <div>
      <Head>
        <title>Alpha Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center mt-5">
        <div className="relative w-full max-w-lg">
          <div className="absolute top-0 -left-4 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-sm"></div>

          <div className="absolute top-0 -right-4 w-72 h-72 bg-yellow-300 rounded-full mix-blend-multiply filter blur-sm"></div>

          <div className="absolute left-20 top-5 -bottom-8 w-72 h-72 bg-[#22cc99] rounded-full mix-blend-multiply filter blur-sm"></div>
        </div>

        {user && <p>wlcome to next {user?.displayName}</p>}
      </main>
    </div>
  );
};

export default Home;
